version: '3.9'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    networks:
      - micro_net

  driver-service:
    build: ./driver-service
    container_name: driver-service
    depends_on:
      - auth-service
    ports:
      - "5001:5001"
    networks:
      - micro_net

  rider-service:
    build: ./rider-service
    container_name: rider-service
    depends_on:
      - auth-service
    ports:
      - "5002:5002"
    networks:
      - micro_net

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - auth-service
      - driver-service
      - rider-service
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
